name = "Guards"
uuid = "4870c19d-3b63-4bfc-b854-f41d47798bf9"
authors = ["Paul Bayer"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
